version: '3.8'

services:
  sound_player:
    # 1. Говорим Docker собрать образ из текущей папки (где лежит Dockerfile)
    build: .
    
    # 2. Даем контейнеру понятное имя
    container_name: soundcloud-app
    
    # 3. Пробрасываем порты (внешний:внутренний)
    ports:
      - "5000:5000"
    
    # 4. Монтируем папки для музыки и обложек (Магия: точка "." везде означает текущую папку!)
    volumes:
      - ./music:/app/music
      - ./covers:/app/covers
    
    # 5. Политика перезапуска: если сайт упадет от ошибки, Docker сам поднимет его
    restart: unless-stopped

